""" Settings for the project """

project = {
    "number_of_lines": 10,
    "hours": 71,
    "memory": "5MB",
    "input_file_extension": ".glo",
    "output_file_extensions": [".csv", ".frq"],
    "constraints": ["clk", "epyc", "none"],
    "N": 12,
    "Runs": 30,
    "Time": 21,
    "Periods": 3,
    "qBMutationSize": -6,
    "GrainMutationSize": -6,
    "DeathRate": -7,
    "GroupSize": 2,
    "Cost": -15,
    "alpha_min": 0.1,
    "alpha_max": 0.9,
    "loges_min": -5.0,
    "loges_max": 5.0,
    "Given": 1.0,
    "grid": 21,
    "bins": 64,
}
