""" Figure settings. """

COLOR_MAP = "RdBu_r"
PLOT_SIZE = 1
SPACING = PLOT_SIZE * 0.75 / 4
LEFT_MARGIN = PLOT_SIZE * 2.5 / 4
RIGHT_MARGIN = PLOT_SIZE * 4.0 / 4
TOP_MARGIN = PLOT_SIZE * 2.5 / 4
BOTTOM_MARGIN = PLOT_SIZE * 2.5 / 4
BORDER_WIDTH = PLOT_SIZE * 0.1 / 4
LINE_WIDTH = PLOT_SIZE * 0.2 / 4
X_LABEL = r"Substitutability of $\it{B}$"
Y_LABEL = r"Influence of $\it{B}$"
X_LABEL_SIZE = PLOT_SIZE * 1.8 / 4
Y_LABEL_SIZE = PLOT_SIZE * 2.0 / 4
BIG_LABEL_SIZE = PLOT_SIZE * 9
LETTER_LABEL_SIZE = PLOT_SIZE * 8
LETTER_POSITION = 0.035
TITLE_PADDING = PLOT_SIZE * 11 / 4
TICK_LABEL_SIZE = PLOT_SIZE * 6
TICK_SIZE = PLOT_SIZE * 1.5
TICK_COLOR = "lightgrey"
PRINT_FOLDER = False
